databases:
  - name: costohealthapp
    databaseName: costohealthapp
    user: costohealthapp
    plan: free

services:
  - type: web
    name: costohealthapp
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    # preDeployCommand: './bin/rails db:migrate' # preDeploymentCommand only available on paid instance types
    startCommand: './bin/rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: costohealthapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

        