databases:
  -name: Costo-api
  databaseName: Costo-api
  user: Costo-db
  plan: free

services:
  - type: web
    name: Costo-api
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    # preDeployCommand: './bin/rails db:migrate' # preDeploymentCommand only available on paid instance types
    startCommand: './bin/rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Costo-api
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

        